"""empty message

Revision ID: 0f45b6a57aaa
Revises: 41edb9b422b5
Create Date: 2023-11-17 19:30:47.576408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f45b6a57aaa'
down_revision = '41edb9b422b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enquiries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('message', sa.String(length=450), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('reward_link',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('reward_duration',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('reward_duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('reward_link',
               existing_type=sa.VARCHAR(),
               nullable=False)

    op.drop_table('enquiries')
    # ### end Alembic commands ###
