"""empty message

Revision ID: 41edb9b422b5
Revises: f43a3873ef96
Create Date: 2023-11-16 08:43:16.651411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41edb9b422b5'
down_revision = 'f43a3873ef96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('reward_link', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('reward_duration', sa.Integer(), nullable=False))
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('frequency',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('reward_duration')
        batch_op.drop_column('reward_link')
        batch_op.drop_column('reward_name')

    # ### end Alembic commands ###
