"""empty message

Revision ID: 601a7d97fdcc
Revises: 98e2264bbf60
Create Date: 2023-11-02 10:08:42.887024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '601a7d97fdcc'
down_revision = '98e2264bbf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_value', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('time_spent_secs', sa.Integer(), nullable=False),
    sa.Column('work_time_secs', sa.Integer(), nullable=False),
    sa.Column('fun_time_secs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=250), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_name')
        batch_op.drop_column('name')

    op.drop_table('session')
    op.drop_table('test')
    # ### end Alembic commands ###
